### ISSUE TITLE
HAGO Todo Items Tracking

### ISSUE THREAD

**Issue by ZihengJiang** [ZihengJiang/tvm-hago#1]
This issue is used to track all unresolved todo items in HAGO before public.

## TODOs

- [x] Fix accuracy for quantized model
- [x] Integrate QNN into the realization part
- [ ] Set up testings
- [x] Add avg_min_max for calibration
- [x] Integrate KL threshold estimation
- [ ] Move previous search methods to the new Tuner API
- [x] Quantized concatenate

## Benchmark

- [ ] Accuracy on common vision models
  - [x] ResNet18
  - [x] ResNet50
  - [ ] ResNet101
  - [x] VGG
  - [x] InceptionV3
- [x] Performance on various hardwares
  - [x] x86 CPU
  - [x] ARM CPU
  - [x] NVIDIA GPU

## Future Works
Items that we may want to do in the future, but no necessary before public:
- Per-channel scales and MobileNet evaluation
- Evaluate need of asymmetric
- Support object detection models
- Investigate overfitting problem during search
- Performance evaluation on accelerators
- Quantized language models
- More customizability:
  - users can register their own threshold functions
